name: CI

on:
  push:
  pull_request:

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t aceest-fitness:${{ github.sha }} .

      - name: Run tests inside the image
        run: docker run --rm aceest-fitness:${{ github.sha }} pytest -q
